name: Deploy
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy and Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          debug: true
          script: |
            cd ${{ secrets.DIR }}
            git pull
#  pm2-configuration:
#    runs-on: ubuntu-latest
#    needs: deploy
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#      - run: npm install pm2@latest -g
#      - run: pm2 -V
#      - run: pm2 start dist/index.js
