name: Deploy
on:
  push:
    branches: [ master ]
jobs:
#  convert-form-ts-to-js:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Get repo code
#        uses: actions/checkout@v3
#      - name: Install dependencies
#        run: npm ci
#      - name: convert form ts to js
#        run: npm run tsc
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy and Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.PASSWORD }}
          debug: true
          command_timeout: 20m
          script: |
            cd ${{ secrets.DIR }}
            git pull
            npm run tsc
            pm2 restart index
            pm2 start dist/index.js

