name: Update Server
on: push
jobs:
  toTSC:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: convert form ts to js
        run: tsc

